version: "3.9"
services:
  sport-classification-model:
    image: sport-classification-model:v1
  sport-classification-gateway:
    image: sport-classification-gateway:v1
    environment:
      - TF_SERVING_HOST=sport-classification-model:8500
    ports:
      - "9696:9696"