apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sports-classification-eks
  region: us-east-2

nodeGroups:
  - name: default-group
    instanceType: t3.medium
    desiredCapacity: 1